CREATE TABLE Comments ([CommentID] counter primary key,[UserID] integer not null default 0,[PostID] integer not null,[Name] varchar(60) not null,[Comment] memo not null,[Email] varchar(160) not null,[WebPage] varchar(160),[Ip] varchar(15) not null default "0.0.0.0",[CreateDate] datetime default now() not null,[Approve] bit not null default 0,[NotifyMe] bit not null default 0)
CREATE TABLE Links ([LinkID] counter primary key,[Name] varchar(100) not null,[Url] varchar(160) not null,[Description] memo,[Target] varchar(50) not null default "_blank",[TermID] integer not null default 0)
CREATE TABLE Posts ([PostID] counter primary key,[UserID] integer not null,[Title] varchar(255) not null,[Content] memo not null,[Code] varchar(255),[State] smallint not null default 0,[AddComment] bit not null default 0,[CreateDate] datetime not null default now(),[ModifyDate] datetime,[Type] smallint not null default 0,[ReadCount] int not null default 0,[Show] smallint not null default 1)
CREATE TABLE Settings ([SettingID] counter primary key,[Name] varchar(100) not null,[Value] memo not null,[Title] varchar(120),[Description] memo,[Main] bit not null default 0,[Sort] integer not null default 0,[Visible] bit not null default 1) 
CREATE TABLE Terms ([TermID] counter primary key,[Name] varchar(80) not null,[Description] varchar(160),[Code] varchar(80) not null,[Type] varchar(12) not null,[SubID] integer not null default 0)
CREATE TABLE TermsTo ([TermsToID] counter primary key,[ObjectID] integer not null,[TermID] int not null,[Type] varchar(12) not null)
CREATE TABLE Users ([UserID] counter primary key,[UserName] varchar(16) not null,[Password] varchar(32) not null,[Name] varchar(60) not null,[Email] varchar(255) not null,[WebPage] varchar(255),[CreateDate] datetime not null default now(),[LastLoginDate] datetime,[State] smallint not null default 0,[Role] varchar(16) not null default "user")
CREATE TABLE Widgets ([WidgetID] counter primary key,[Title] varchar(160) not null,[Description] memo,[FolderName] varchar(160),[Type] smallint,[Sort] integer not null default 0,[Visible] bit not null default 1,[PlaceHolder] varchar(50) not null default "Default")
INSERT INTO Posts(UserID,Title,Content,Code,State,AddComment,Type) Values(1,'{post-title}','{post-content}','{post-code}',1,1,0)
INSERT INTO Posts(UserID,Title,Content,Code,State,Type,Show) Values(1,'{page-title}','{page-content}','{page-code}',1,1,0)
INSERT INTO Terms([Name],Code,Type) Values('{category-title}','{category-code}','category')
INSERT INTO Terms([Name],Code,Type) Values('{tag-title}','{tag-code}','tag')
INSERT INTO Settings([Name],[Value],[Title],[Main],[Sort],[Visible],[Description]) Values('blog_name','{setting-blogname}','BlogName',1,1,1,'BlogNameDescription')
INSERT INTO Settings([Name],[Value],[Title],[Main],[Sort],[Visible],[Description]) Values('blog_description','{setting-blogdescription}','BlogDescription',1,2,1,'BlogDescriptionDescription')
INSERT INTO Settings([Name],[Value],[Title],[Main],[Sort],[Visible],[Description]) Values('blog_url','{0}','BlogUrl',1,3,1,'BlogUrlDescription')
INSERT INTO Settings([Name],[Value],[Title],[Main],[Sort],[Visible],[Description]) Values('language','{1}','BlogLanguage',1,5,1,'BlogLanguageDescription')
INSERT INTO Settings([Name],[Value],[Title],[Main],[Sort],[Visible],[Description]) Values('theme','Classic','',1,6,0,'')
INSERT INTO Settings([Name],[Value],[Title],[Main],[Sort],[Visible],[Description]) Values('permalink','0','BlogPermalink',1,9,1,'BlogPermalinkDescription')
INSERT INTO Settings([Name],[Value],[Title],[Main],[Sort],[Visible],[Description]) Values('permaexpression','{name}.html','',1,0,1,'')
INSERT INTO Settings([Name],[Value],[Title],[Main],[Sort],[Visible],[Description]) Values('show_post_count','10','BlogShowPostCount',1,10,1,'BlogShowPostCountDescription')
INSERT INTO Settings([Name],[Value],[Title],[Main],[Sort],[Visible],[Description]) Values('add_comment_approve','0','BlogAddCommentApprove',1,11,1,'BlogAddCommentApproveDescription')
INSERT INTO Settings([Name],[Value],[Title],[Main],[Sort],[Visible],[Description]) Values('recent_posts_count','5','BlogRecentPostCount',1,12,1,'BlogRecentPostCountDescription')
INSERT INTO Settings([Name],[Value],[Title],[Main],[Sort],[Visible],[Description]) Values('recent_comments_count','5','BlogRecentCommentsCount',1,13,1,'BlogRecentCommentsCountDescription')
INSERT INTO Settings([Name],[Value],[Title],[Main],[Sort],[Visible],[Description]) Values('pagingstyle','8','PagingStyle',1,14,1,'PagingStyleDescription')
INSERT INTO Settings([Name],[Value],[Title],[Main],[Sort],[Visible],[Description]) Values('paging','true','Paging',1,15,1,'PagingDescription')
INSERT INTO Settings([Name],[Value],[Title],[Main],[Sort],[Visible],[Description]) Values('comment_sendmail','true','',1,16,1,'')
INSERT INTO Settings([Name],[Value],[Title],[Main],[Sort],[Visible],[Description]) Values('feed_url','{0}feed.aspx','',1,17,1,'')
INSERT INTO Settings([Name],[Value],[Title],[Main],[Sort],[Visible],[Description]) Values('smtp_name','example','',1,0,1,'')
INSERT INTO Settings([Name],[Value],[Title],[Main],[Sort],[Visible],[Description]) Values('smtp_email','example@example.com','',1,0,1,'')
INSERT INTO Settings([Name],[Value],[Title],[Main],[Sort],[Visible],[Description]) Values('smtp_server','mail.example.com','',1,0,1,'')
INSERT INTO Settings([Name],[Value],[Title],[Main],[Sort],[Visible],[Description]) Values('smtp_port','25','',1,0,1,'')
INSERT INTO Settings([Name],[Value],[Title],[Main],[Sort],[Visible],[Description]) Values('smtp_user','user@example.com','',1,0,1,'')
INSERT INTO Settings([Name],[Value],[Title],[Main],[Sort],[Visible],[Description]) Values('smtp_pass','password','',1,0,1,'')
INSERT INTO Settings([Name],[Value],[Title],[Main],[Sort],[Visible],[Description]) Values('smtp_usessl','false','',1,0,1,'')
INSERT INTO TermsTo([TermID],[ObjectID],[Type]) Values(1,1,'category')
INSERT INTO TermsTo([TermID],[ObjectID],[Type]) Values(2,1,'tag')
INSERT INTO Users([UserName],[Password],[Name],[Email],[State],[Role]) Values('admin','e10adc3949ba59abbe56e057f20f883e','Admin','example@example.com',10,'admin')
INSERT INTO Widgets([Title],[FolderName],[Type],[Sort],[Visible],[PlaceHolder]) Values('{widget-feeder}','Feeder',0,0,1,'Default')
INSERT INTO Widgets([Title],[FolderName],[Type],[Sort],[Visible],[PlaceHolder]) Values('{widget-pages}','Pages',0,1,1,'Default')
INSERT INTO Widgets([Title],[FolderName],[Type],[Sort],[Visible],[PlaceHolder]) Values('{widget-categories}','Categories',0,3,1,'Default')
INSERT INTO Widgets([Title],[FolderName],[Type],[Sort],[Visible],[PlaceHolder]) Values('{widget-recentpost}','RecentPost',0,4,1,'Default')
INSERT INTO Widgets([Title],[FolderName],[Type],[Sort],[Visible],[PlaceHolder]) Values('{widget-recentcomment}','RecentComment',0,5,1,'Default')
INSERT INTO Widgets([Title],[FolderName],[Type],[Sort],[Visible],[PlaceHolder]) Values('{widget-links}','Links',0,6,1,'Default')
INSERT INTO Links([Name],[Url],[Description],[Target]) Values('Blogsa.Net','http://www.blogsa.net','Blogsa.Net','_blank')
